"""add consents

Revision ID: 14d02830d474
Revises: 3e24005089f4
Create Date: 2026-08-21 02:26:07.787398

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '14d02830d474'
down_revision: Union[str, Sequence[str], None] = '3e24005089f4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('consents',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('subject_id', sa.String(length=36), nullable=False),
    sa.Column('purpose', sa.Enum('PREDICTION', 'TIMELINE', 'PERSONALIZATION', 'BUSINESS_SHARING', name='consentpurpose'), nullable=False),
    sa.Column('granted', sa.Boolean(), nullable=False),
    sa.Column('granted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_consents_subject_id'), 'consents', ['subject_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_consents_subject_id'), table_name='consents')
    op.drop_table('consents')
    # ### end Alembic commands ###
