"""add learning insight counts

Revision ID: 3e24005089f4
Revises: 45ac544a4d23
Create Date: 2026-08-20 16:17:08.777317

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3e24005089f4'
down_revision: Union[str, Sequence[str], None] = '45ac544a4d23'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('homes',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('home_type', sa.String(length=50), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('learning_insights',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('target', sa.String(), nullable=False),
    sa.Column('signal_name', sa.String(), nullable=False),
    sa.Column('sample_size', sa.Integer(), nullable=False),
    sa.Column('correct_count', sa.Integer(), nullable=False),
    sa.Column('incorrect_count', sa.Integer(), nullable=False),
    sa.Column('accuracy', sa.Float(), nullable=False),
    sa.Column('insight', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_learning_insights_signal_name'), 'learning_insights', ['signal_name'], unique=False)
    op.create_index(op.f('ix_learning_insights_target'), 'learning_insights', ['target'], unique=False)
    op.create_table('home_information',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('home_id', sa.String(length=36), nullable=False),
    sa.Column('country', sa.String(length=100), nullable=False),
    sa.Column('city', sa.String(length=100), nullable=False),
    sa.Column('address', sa.String(length=255), nullable=False),
    sa.Column('postcode', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['home_id'], ['homes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_home_information_home_id'), 'home_information', ['home_id'], unique=False)
    op.create_table('home_state',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('home_id', sa.String(length=36), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.ForeignKeyConstraint(['home_id'], ['homes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_home_state_home_id'), 'home_state', ['home_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_home_state_home_id'), table_name='home_state')
    op.drop_table('home_state')
    op.drop_index(op.f('ix_home_information_home_id'), table_name='home_information')
    op.drop_table('home_information')
    op.drop_index(op.f('ix_learning_insights_target'), table_name='learning_insights')
    op.drop_index(op.f('ix_learning_insights_signal_name'), table_name='learning_insights')
    op.drop_table('learning_insights')
    op.drop_table('homes')
    # ### end Alembic commands ###
