"""add learning records

Revision ID: 45ac544a4d23
Revises: 019ba7475f33
Create Date: 2026-08-19 09:20:40.163017

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '45ac544a4d23'
down_revision: Union[str, Sequence[str], None] = '019ba7475f33'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('learning_records',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('prediction_id', sa.String(), nullable=False),
    sa.Column('outcome_id', sa.String(), nullable=False),
    sa.Column('evaluation_id', sa.String(), nullable=False),
    sa.Column('target', sa.String(), nullable=False),
    sa.Column('correct', sa.Boolean(), nullable=False),
    sa.Column('signal_names', sa.JSON(), nullable=False),
    sa.Column('signal_values', sa.JSON(), nullable=False),
    sa.Column('signal_strengths', sa.JSON(), nullable=False),
    sa.Column('signal_confidences', sa.JSON(), nullable=False),
    sa.Column('intent_score', sa.Float(), nullable=False),
    sa.Column('prediction_confidence', sa.Float(), nullable=False),
    sa.Column('lesson', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_learning_records_evaluation_id'), 'learning_records', ['evaluation_id'], unique=False)
    op.create_index(op.f('ix_learning_records_outcome_id'), 'learning_records', ['outcome_id'], unique=False)
    op.create_index(op.f('ix_learning_records_prediction_id'), 'learning_records', ['prediction_id'], unique=False)
    

def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_learning_records_prediction_id'), table_name='learning_records')
    op.drop_index(op.f('ix_learning_records_outcome_id'), table_name='learning_records')
    op.drop_index(op.f('ix_learning_records_evaluation_id'), table_name='learning_records')
    op.drop_table('learning_records')
    
    # ### end Alembic commands ###
