"""add home property references

Revision ID: 77f243fe6432
Revises: f451eb88b214
Create Date: 2026-08-29 12:16:00.740703

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '77f243fe6432'
down_revision: Union[str, Sequence[str], None] = 'f451eb88b214'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('home_property_references',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('home_id', sa.String(length=36), nullable=False),
    sa.Column('uprn', sa.String(length=100), nullable=False),
    sa.ForeignKeyConstraint(['home_id'], ['homes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_home_property_references_home_id'), 'home_property_references', ['home_id'], unique=True)
    op.create_index(op.f('ix_home_property_references_uprn'), 'home_property_references', ['uprn'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_home_property_references_uprn'), table_name='home_property_references')
    op.drop_index(op.f('ix_home_property_references_home_id'), table_name='home_property_references')
    op.drop_table('home_property_references')
    # ### end Alembic commands ###
