"""add audit records

Revision ID: 79de480bca4c
Revises: 14d02830d474
Create Date: 2026-08-21 05:58:55.717728

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '79de480bca4c'
down_revision: Union[str, Sequence[str], None] = '14d02830d474'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_records',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('event_type', sa.String(), nullable=False),
    sa.Column('event_name', sa.String(), nullable=False),
    sa.Column('state', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.Column('subject_id', sa.String(), nullable=False),
    sa.Column('resource_id', sa.String(), nullable=True),
    sa.Column('resource_type', sa.String(), nullable=True),
    sa.Column('occurred_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('details', sa.JSON(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_records_event_name'), 'audit_records', ['event_name'], unique=False)
    op.create_index(op.f('ix_audit_records_event_type'), 'audit_records', ['event_type'], unique=False)
    op.create_index(op.f('ix_audit_records_occurred_at'), 'audit_records', ['occurred_at'], unique=False)
    op.create_index(op.f('ix_audit_records_resource_id'), 'audit_records', ['resource_id'], unique=False)
    op.create_index(op.f('ix_audit_records_subject_id'), 'audit_records', ['subject_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_audit_records_subject_id'), table_name='audit_records')
    op.drop_index(op.f('ix_audit_records_resource_id'), table_name='audit_records')
    op.drop_index(op.f('ix_audit_records_occurred_at'), table_name='audit_records')
    op.drop_index(op.f('ix_audit_records_event_type'), table_name='audit_records')
    op.drop_index(op.f('ix_audit_records_event_name'), table_name='audit_records')
    op.drop_table('audit_records')
    # ### end Alembic commands ###
