"""add maintenance records

Revision ID: 9fc242e9e579
Revises: 79de480bca4c
Create Date: 2026-08-21 12:00:04.051564

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9fc242e9e579'
down_revision: Union[str, Sequence[str], None] = '79de480bca4c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('maintenance_records',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('subject_id', sa.String(), nullable=False),
    sa.Column('home_id', sa.String(), nullable=False),
    sa.Column('task', sa.String(), nullable=False),
    sa.Column('maintenance_type', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('scheduled_for', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('evidence', sa.JSON(), nullable=False),
    sa.Column('metadata', sa.JSON(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_maintenance_records_home_id'), 'maintenance_records', ['home_id'], unique=False)
    op.create_index(op.f('ix_maintenance_records_subject_id'), 'maintenance_records', ['subject_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_maintenance_records_subject_id'), table_name='maintenance_records')
    op.drop_index(op.f('ix_maintenance_records_home_id'), table_name='maintenance_records')
    op.drop_table('maintenance_records')
    # ### end Alembic commands ###
