"""add memory lifecycle fields

Revision ID: a5a34e2953e4
Revises: 203843b0b571
Create Date: 2026-08-08 07:05:00.971351

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a5a34e2953e4'
down_revision: Union[str, Sequence[str], None] = '203843b0b571'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('memory_entries', sa.Column('importance', sa.Float(), nullable=False))
    op.add_column('memory_entries', sa.Column('access_count', sa.Integer(), nullable=False))
    op.add_column('memory_entries', sa.Column('last_accessed_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('memory_entries', 'last_accessed_at')
    op.drop_column('memory_entries', 'access_count')
    op.drop_column('memory_entries', 'importance')
    # ### end Alembic commands ###
