"""add intelligence outcomes

Revision ID: a787c0a13557
Revises: a5a34e2953e4
Create Date: 2026-08-08 10:59:25.806355

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a787c0a13557'
down_revision: Union[str, Sequence[str], None] = 'a5a34e2953e4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('intelligence_outcomes',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('prediction_id', sa.String(), nullable=False),
    sa.Column('subject_id', sa.String(), nullable=False),
    sa.Column('target', sa.String(), nullable=False),
    sa.Column('occurred', sa.Boolean(), nullable=False),
    sa.Column('observed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('details', sa.JSON(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_intelligence_outcomes_prediction_id'), 'intelligence_outcomes', ['prediction_id'], unique=False)
    op.create_index(op.f('ix_intelligence_outcomes_subject_id'), 'intelligence_outcomes', ['subject_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_intelligence_outcomes_subject_id'), table_name='intelligence_outcomes')
    op.drop_index(op.f('ix_intelligence_outcomes_prediction_id'), table_name='intelligence_outcomes')
    op.drop_table('intelligence_outcomes')
    # ### end Alembic commands ###
