"""add telegram identities

Revision ID: c8b9cce4753c
Revises: 7f4ef2d4e356
Create Date: 2026-10-07 01:21:52.000185

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'c8b9cce4753c'
down_revision: Union[str, Sequence[str], None] = '7f4ef2d4e356'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('telegram_identities',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('telegram_user_id', sa.String(length=100), nullable=False),
    sa.Column('subject_id', sa.String(length=36), nullable=False),
    sa.Column('home_id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_telegram_identities_home_id'), 'telegram_identities', ['home_id'], unique=False)
    op.create_index(op.f('ix_telegram_identities_subject_id'), 'telegram_identities', ['subject_id'], unique=False)
    op.create_index(op.f('ix_telegram_identities_telegram_user_id'), 'telegram_identities', ['telegram_user_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    op.drop_index(
        op.f('ix_telegram_identities_telegram_user_id'),
        table_name='telegram_identities'
    )
    op.drop_index(
        op.f('ix_telegram_identities_subject_id'),
        table_name='telegram_identities'
    )
    op.drop_index(
        op.f('ix_telegram_identities_home_id'),
        table_name='telegram_identities'
    )
    op.drop_table('telegram_identities')